# Generated by Django 3.2.9 on 2021-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
