# Generated by Django 3.2.9 on 2021-12-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_perfil_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='profesor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
