# Generated by Django 3.2.9 on 2021-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(default='profesor', max_length=30),
            preserve_default=False,
        ),
    ]
