# Generated by Django 3.2.9 on 2021-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
