# Generated by Django 3.2.9 on 2021-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_curso_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='avatar',
            field=models.ImageField(upload_to='core'),
        ),
    ]
