# Generated by Django 3.2.9 on 2021-12-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_disciplina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disciplina',
        ),
    ]
