# Generated by Django 3.2.9 on 2022-01-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_inscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inscripcion',
        ),
    ]
